Repository Nexters/JYP-iOS, pull requests merged in 2022-11, with the labels that each got.

#84 Feat/#77 토론장 입장 코드 바텀시트 구현
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_key.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_key.imageset/icon_key.svg
  JYP-iOS/JYP-iOS/Sources/Extension/Notification+Name+Ext.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/JoinPlanner/JoinPlannerBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/InputPlannerCodeBottomSheetReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/InputPlannerCodeBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/SelectionPlannerJoinBottomViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
  JYP-iOS/JYP-iOS/Sources/SceneDelegate.swift
Labels: size/l

#87 [Feat/#86] 토론장 UI 수정
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_invite.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_invite.imageset/Group 80100 (1).svg
  JYP-iOS/JYP-iOS/Sources/Base/NavigationBarViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/TempViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Components/OldPlannerHomeDiscussionSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/Components/Cell/CreatePikmiCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/Components/Cell/EmptyTagCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/Components/DiscussionPikmiSectionHeader.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/Components/DiscussionTagSectionHeader.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/DiscussionPikmiSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/DiscussionReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/DiscussionSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/DiscussionTagSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/DiscussionView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/PikiCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/PikiCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlanReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlanView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/PlannerReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/PlannerViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/TagBottomSheet/TagBottomSheetReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/TagBottomSheet/TagBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPInviteStackView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPTagProfileStackView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/TabBar/TabBarViewController.swift
Labels: size/xl

#89 [Feat/#88] 네트워크 API 로직 구현
  JYP-iOS/JYP-iOS/Sources/Model/BaseModel.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/AddPikmiResponse.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/CreateJourneyRequest.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/CreateJourneyResponse.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/CreateJourneyUserRequest.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/CreatePikmiRequest.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/CreateUserRequest.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/EditPikisResponse.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/EditUserRequest.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/FetchJourneysResponse.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/FetchTagsRequest.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/FetchTagsResponse.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/UpdatePikisRequest.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/UpdateTagsRequest.swift
  JYP-iOS/JYP-iOS/Sources/Model/Journey.swift
  JYP-iOS/JYP-iOS/Sources/Model/PersonalityID.swift
  JYP-iOS/JYP-iOS/Sources/Model/PersonalityId.swift
  JYP-iOS/JYP-iOS/Sources/Model/Pik.swift
  JYP-iOS/JYP-iOS/Sources/Model/User.swift
  JYP-iOS/JYP-iOS/Sources/Network/API/JourneyAPI.swift
  JYP-iOS/JYP-iOS/Sources/Network/API/UserAPI.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/JourneyService.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/UserService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/TempViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/InputPlannerCodeBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/ScheduledJourney/ScheduledJourneyReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingQuestionReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingSignUp/OnboardingSignUpReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingSignUp/OnboardingSignUpViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingTwo/OnboardingTwoViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/DiscussionReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/EmptyPikiCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/PikiCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/PlanCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlanReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlanSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlanView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/PlannerReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/PlannerViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/TabBar/TabBarViewController.swift
Labels: size/xl

#90 Feat/#85 나의 플래너 API 연결
  JYP-iOS/JYP-iOS/Sources/Extension/DateManager.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/FetchJourneysResponse.swift
  JYP-iOS/JYP-iOS/Sources/Model/PersonalityID.swift
  JYP-iOS/JYP-iOS/Sources/Model/ThemeType.swift
  JYP-iOS/JYP-iOS/Sources/Network/API/JourneyAPI.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/JourneyService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/Cell/JourneyCardCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/PastJourney/PastJourneyReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/PastJourney/PastJourneyView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/ScheduledJourney/ScheduledJourneyReactor.swift
Labels: size/m
