Repository Nexters/JYP-iOS, pull requests merged in 2022-08, with the labels that each got.

#20 [Feat/#16] 공통 네비게이션 바 & 재사용 버튼 구현 $ 리엑토 킷 예시
  JYP-iOS/JYP-iOS/Sources/AppDelegate.swift
  JYP-iOS/JYP-iOS/Sources/Base/NavigationBarViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/MyPageViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingLiking/OnboardingLikingReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingLiking/OnboardingLikingView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingLiking/OnboardingLikingViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingPlace/OnboardingPlaceReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingPlace/OnboardingPlaceView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingPlace/OnboardingPlaceViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/NavigationBar.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlace/SearchPlaceViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlaceDetail/SearchPlaceDetailViewController.swift
Labels: size/l

#23 [Feat/#22] 온보딩 페이지 UI
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/kakao_login.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/kakao_login.imageset/kakao_login_large_wide 1.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/kakao_login.imageset/kakao_login_large_wide 1@2x.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/kakao_login.imageset/kakao_login_large_wide 1@3x.png
  JYP-iOS/JYP-iOS/Sources/Base/NavigationBarViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingCardView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingHowToNewPlace/OnboardingHowToNewPlaceReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingHowToNewPlace/OnboardingHowToNewPlaceViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingLiking/OnboardingLikingView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingPlace/OnboardingPlaceReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingPlace/OnboardingPlaceView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingPlace/OnboardingPlaceViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingQuestionView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingSignUp/OnboardingSignUpReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingSignUp/OnboardingSignUpView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingSignUp/OnboardingSignUpViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingWhatIsJourney/OnboardingWhatIsJourneyReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingWhatIsJourney/OnboardingWhatIsJourneyViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingWhenJourneyPlan/OnboardingWhenJourneyPlanReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingWhenJourneyPlan/OnboardingWhenJourneyPlanViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
  Project.swift
Labels: size/xl

#24 [Feat/#12] 날짜 선택 UI 개발 #1
  JYP-iOS/JYP-iOS/Sources/Extension/DateManager.swift
  JYP-iOS/JYP-iOS/Sources/Extension/Rx+Ext.swift
  JYP-iOS/JYP-iOS/Sources/Extension/UIView+Ext.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/BottomSheet/BottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Calendar/CalendarService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Calendar/CalendarViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Calendar/CalenderReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/Components/JYPDateTextField.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerDateReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerDateViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/CalendarViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingPlace/OnboardingPlaceReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingViewController.swift
Labels: size/xl

#30 [Feat/#25] 플래너 날짜 선택 UI 기능 구현
  JYP-iOS/JYP-iOS/Sources/Presenter/BottomSheet/BottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Calendar/CalendarService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Calendar/CalendarViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Calendar/CalenderReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/Components/JYPDateTextField.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerDateReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerDateView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerDateViewController.swift
Labels: size/m

#31 [Feat/#28] 플래너 토론장 UI #2
  JYP-iOS/JYP-iOS/Sources/Base/BaseCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionHome/Components/EmptyCollectionReusableView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionHome/Components/JourneyPlaceCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionHome/Components/JourneyTagCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionHome/Components/TagView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionHome/DiscussionHomeView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionHome/DiscussionHomeViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionHome/TagViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionInvite/DiscussionInviteView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionInvite/DiscusstionInviteViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionPlaceMap/DiscussionPlaceMapViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionPlaceMap/WebViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionSearchPlace/DiscussionSearchPlaceTableViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionSearchPlace/DiscussionSearchPlaceViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPSearchTextField.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlace/Component/SearchPlaceResultTableViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Service/BaseService.swift
  JYP-iOS/JYP-iOS/Sources/Service/KakaoSearchService.swift
  JYP-iOS/JYP-iOS/Sources/Service/ServiceProviderType.swift
  Project.swift
Labels: size/xl

#34 [Feat/#29] 여행 태그 선택 뷰 UI
  JYP-iOS/JYP-iOS/Sources/Model/Tag.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/Components/PlannerTagCollectionReusableView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/TagSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerViewController.swift
  Project.swift
  Tuist/Dependencies.swift
Labels: size/m

#37 [Feat/#32] 플래너 - 토론장 첫 진입 기능 구현 #1
  .swiftlint.yml
  JYP-iOS/JYP-iOS/Sources/Base/NavigationBarViewController.swift
  JYP-iOS/JYP-iOS/Sources/Extension/UIImage+Ext.swift
  JYP-iOS/JYP-iOS/Sources/Model/CandidatePlace.swift
  JYP-iOS/JYP-iOS/Sources/Model/JYP/JYPCategory.swift
  JYP-iOS/JYP-iOS/Sources/Model/Tag.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionHome/Components/EmptyCollectionReusableView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionHome/Components/JourneyTagCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionHome/DiscussionHomeViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionHome/TagViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Discussion/DiscussionInvite/DiscusstionInviteViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/MyPageViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerHome/Components/ImageBox.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerHome/Components/PlannerHomeDiscussionCandidatePlaceSectionHeader.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerHome/Components/PlannerHomeDiscussionJYPTagSectionHeader.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerHome/Components/PlannerHomeDiscussionSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerHome/PlannerHomeDiscussionBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerHome/PlannerHomeReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerHome/PlannerHomeViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerInvite/PlannerInviteViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerSearchPlace/PlannerSearchPlaceTableViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerSearchPlace/PlannerSearchPlaceViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerSearchPlaceMap/PlannerSearchPlaceMapViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerSearchPlaceWeb/PlannerSearchPlaceWebViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/CandidatePlaceCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/CandidatePlaceCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/CreateCandidatePlaceCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/CreateCandidatePlaceCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/JYPTagCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/JYPTagCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPTag.swift
  JYP-iOS/JYP-iOS/Sources/Service/ServiceProviderType.swift
Labels: size/xl

#38 [Feat/#36] 여행 태그 선택 기능 구현
  JYP-iOS/JYP-iOS/Sources/Model/Tag.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/TagSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/JYPTagCollectionViewCell.swift
Labels: size/m

#41 [Feat/#35] 좋아요 / 싫어요 태그 추가 바텀시트 연결
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/AddTagBottomSheet/AddTagBottomSheetReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/AddTagBottomSheet/AddTagBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/Components/PlannerTagCollectionReusableView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerDate/CreatePlannerDateReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerDate/CreatePlannerDateView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerDate/CreatePlannerDateViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPSearchTextField.swift
Labels: size/m

#43 [Feat/#40] 플래너 - 토론장 기능 구현
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_vote_active.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_vote_active.imageset/Group 80219.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_vote_active.imageset/Group 80219@2x.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_vote_active.imageset/Group 80219@3x.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_vote_inactive.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_vote_inactive.imageset/Group 80290.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_vote_inactive.imageset/Group 80290@2x.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_vote_inactive.imageset/Group 80290@3x.png
  JYP-iOS/JYP-iOS/Sources/Model/CandidatePlace.swift
  JYP-iOS/JYP-iOS/Sources/Model/JYP/JYPCategory.swift
  JYP-iOS/JYP-iOS/Sources/Model/Journey.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/BaseService.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/JourneyService.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/KakaoSearchService.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/ServiceProviderType.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerHome/PlannerHomeReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerHome/PlannerHomeViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerSearchPlaceMap/PlannerSearchPlaceMapViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/CandidatePlaceCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/CandidatePlaceCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPTag.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPTagBottomSheetReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPTagBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/WebReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/WebViewController.swift
Labels: size/l

#45 [Feat/#42] 태그 추가 로직 구현
  JYP-iOS/JYP-iOS/Sources/Network/Service/ServiceProviderType.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/AddTagBottomSheet/AddTagBottomSheetReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/Components/PlannerTagCollectionReusableView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/TagSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPSearchTextField.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPTag.swift
  JYP-iOS/JYP-iOS/Sources/Service/TagService.swift
Labels: size/s

#47 [Feat/#44] 플래너 장소 검색
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_Public institutions.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_Public institutions.imageset/icon_Public institutions.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_Tourist spot.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_Tourist spot.imageset/icon_Tourist spot.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_bank.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_bank.imageset/icon_bank.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_cafe.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_cafe.imageset/icon_cafe.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_charging zone.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_charging zone.imageset/icon_charging zone.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_convenience store.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_convenience store.imageset/icon_convenience store.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_cultural institution.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_cultural institution.imageset/icon_cultural institution.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_culture place.imageset/icon_culture place.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_etc.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_etc.imageset/icon_etc.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_hospital.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_hospital.imageset/icon_hospital.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_lodgings.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_lodgings.imageset/icon_lodgings.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_market.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_market.imageset/icon_market.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_parking lot.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_parking lot.imageset/icon_parking lot.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_pharmacy.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_pharmacy.imageset/icon_pharmacy.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_restaurant.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_restaurant.imageset/icon_restaurant.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_school.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_school.imageset/icon_school.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_transportation.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_transportation.imageset/icon_transportation.svg
  JYP-iOS/JYP-iOS/Sources/Base/BaseCollectionReusableView.swift
  JYP-iOS/JYP-iOS/Sources/Base/BaseCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Base/BaseTableViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Model/JYP/JYPCategory.swift
  JYP-iOS/JYP-iOS/Sources/Model/kakaoSearchResponse.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/KakaoSearchService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/Components/PlannerTagCollectionReusableView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/OnBoarding/OnboardingCardView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerHome/Components/PlannerHomeDiscussionCandidatePlaceSectionHeader.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerHome/Components/PlannerHomeDiscussionSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerHome/PlannerHomeReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerHome/PlannerHomeViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerSearchPlace/Components/PlannerSearchPlaceSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerSearchPlace/PlannerSearchPlaceReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerSearchPlace/PlannerSearchPlaceViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerSearchPlaceMap/PlannerSearchPlaceMapReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerSearchPlaceMap/PlannerSearchPlaceMapViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/CreateCandidatePlaceCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/KakaoSearchPlaceTableViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/KakaoSearchPlaceTableViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPTagBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/WebViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlace/SearchPlaceViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlaceDetail/SearchPlaceDetailViewController.swift
Labels: size/xl

#49 [Feat#48] lottie 시도
  JYP-iOS/JYP-iOS/Resources/Lottie/like_active_alone.json
  JYP-iOS/JYP-iOS/Resources/Lottie/test_active_other.json
  JYP-iOS/JYP-iOS/Sources/Network/Service/JourneyService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerHome/PlannerHomeReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerHome/PlannerHomeViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/CandidatePlaceCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/CandidatePlaceCollectionViewCellReactor.swift
  Project.swift
  Tuist/Dependencies.swift
Labels: size/s

#50 [Feat/#46] 나의 여행 뷰 #1 (메뉴 버튼 및 Empty Journey Cell 개발)
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/planner_card_start.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/planner_card_start.imageset/Group 80422.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/planner_card_start.imageset/Group 80422@2x.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/planner_card_start.imageset/Group 80422@3x.png
  JYP-iOS/JYP-iOS/Sources/Base/BaseView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/Cell/EmptyJourneyCardCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/Cell/EmptyJourneyCardCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/Cell/JourneyCardCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/Cell/JourneyCardCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/ScheduledJourney/ScheduledJourneyModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/ScheduledJourney/ScheduledJourneyReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/ScheduledJourney/ScheduledJourneyView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPBottomBorderButton.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/TabBar/TabBarViewController.swift
Labels: size/l

#54 [Feat/#52] Line Spacing 조정 Extension 추가
  JYP-iOS/JYP-iOS/Sources/Extension/UILabel+Ext.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerViewController.swift
Labels: size/s

#63 [Feat/#62] 다른 여행기 & 마이페이지 UI 구현
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/another_journey.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/another_journey.imageset/illust_1.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/another_journey.imageset/illust_1@2x.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/another_journey.imageset/illust_1@3x.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/profile_1.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/profile_1.imageset/profile_1.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/profile_2.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/profile_2.imageset/profile_2.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/profile_3.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/profile_3.imageset/profile_3.svg
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/profile_4.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/profile_4.imageset/profile_4.svg
  JYP-iOS/JYP-iOS/Sources/Presenter/AnotherJourney/AnotherJourneyViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/MyPageButton.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/MyPageViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/TempViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/TabBar/TabBarViewController.swift
Labels: size/l

#64 [Feat/#60] 여행 계획 (Journey Plan) #2
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_Modify.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_Modify.imageset/icon_Modify.svg
  JYP-iOS/JYP-iOS/Sources/Model/Journey.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/JourneyService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/DiscussionReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/DayTagCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/DayTagCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/EmptyPikiView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/JourneyPlanCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/JourneyPlanCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/PikiCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/PikiCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/DayTagSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlaceSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlanReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlanSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlanView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/PikiSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/PlannerService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/PlannerViewController.swift
Labels: size/l

#66 Feat/#65 여행 계획 (Journey Plan) #3
  JYP-iOS/JYP-iOS/Sources/Model/Journey.swift
  JYP-iOS/JYP-iOS/Sources/Model/Tag.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/JourneyService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/Cell/JourneyCardCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/ScheduledJourney/ScheduledJourneyReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/DayTagCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/DayTagCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/EmptyPikiCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/JourneyPlanCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/JourneyPlanCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/PikiCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/PikiCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/DayTagSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlanSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlanView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/PikiSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/OldPlannerHomeReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/OldPlannerHomeViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/PlannerService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/PlannerViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/JYPTagCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/TagCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPMemberStackView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPTagBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/TabBar/TabBarViewController.swift
  JYP-iOS/JYP-iOS/Sources/Service/TagService.swift
Labels: size/xl
