Repository Nexters/JYP-iOS, pull requests merged in 2023-01, with the labels that each got.

#96 [Feat/#95] 토론장 네트워크 연동
  JYP-iOS/JYP-iOS/Sources/CompositionRoot.swift
  JYP-iOS/JYP-iOS/Sources/Config/Environment.swift
  JYP-iOS/JYP-iOS/Sources/Extension/Array+Ext.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/CreateUserRequest.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/FetchJourneyDetailResponse.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/UpdatePikisResponse.swift
  JYP-iOS/JYP-iOS/Sources/Network/API/BaseAPI.swift
  JYP-iOS/JYP-iOS/Sources/Network/API/UserAPI.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/JourneyService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/MyPageViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/TempViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/InputPlannerCodeBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/PastJourney/PastJourneyView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/ScheduledJourney/ScheduledJourneyView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/SelectionPlannerJoinBottomViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingQuestionPlan/OnboardingQuestionPlanViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingSignUp/OnboardingSignUpReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingSignUp/OnboardingSignUpViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/DiscussionReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/PikiCollectionReusableView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/PikiCollectionReusableViewReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlanReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlanView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/PlannerReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/PlannerViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerInvite/PlannerInviteReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerInvite/PlannerInviteViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerRoute/PlannerRouteReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerRoute/PlannerRouteViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerSearchPlaceMap/PlannerSearchPlaceMapReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerSearchPlaceMap/PlannerSearchPlaceMapViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlace/Component/SearchPlaceResultTableViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlace/Component/SearchPlaceView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlace/SearchPlaceViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlaceDetail/Component/AddPlaceBox.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlaceDetail/Component/SearchPlaceDetailView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlaceDetail/SearchPlaceDetailViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/SearchPlanner/SearchPlannerViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/TabBar/TabBarViewController.swift
  JYP-iOS/JYP-iOS/Sources/SceneDelegate.swift
Labels: size/xl

#100 [Bug/#98] emptyCell이 나오지 않는 현상 및 만들기 버튼 바인딩
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/Cell/EmptyJourneyCardCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/PastJourney/PastJourneyReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/ScheduledJourney/ScheduledJourneyReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/ScheduledJourney/ScheduledJourneyView.swift
Labels: size/s

#102 [Feat/#97] 참여코드로 플래너 입장 구현
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_x delete.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_x delete.imageset/icon_x delete.svg
  JYP-iOS/JYP-iOS/Sources/Base/NavigationBarViewController.swift
  JYP-iOS/JYP-iOS/Sources/CompositionRoot.swift
  JYP-iOS/JYP-iOS/Sources/Network/API/JourneyAPI.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/JourneyService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerDate/CreatePlannerDateReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerDate/CreatePlannerDateViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/InputPlannerCodeBottomSheetReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/InputPlannerCodeBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/SelectionPlannerJoinBottomViewController.swift
Labels: size/m

#106 [Feat/#105] 온보딩 네트워크 연동
  JYP-iOS/JYP-iOS/Sources/CompositionRoot.swift
  JYP-iOS/JYP-iOS/Sources/Config/Environment.swift
  JYP-iOS/JYP-iOS/Sources/Config/KeychainAccess.swift
  JYP-iOS/JYP-iOS/Sources/Extension/UIViewController+Ext.swift
  JYP-iOS/JYP-iOS/Sources/Model/AuthVendor.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/AppleLoginResponse.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/CreateUserRequest.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/KakaoLoginResponse.swift
  JYP-iOS/JYP-iOS/Sources/Model/DTO/UpdateUserRequest.swift
  JYP-iOS/JYP-iOS/Sources/Model/PersonalityID.swift
  JYP-iOS/JYP-iOS/Sources/Network/API/AuthAPI.swift
  JYP-iOS/JYP-iOS/Sources/Network/API/BaseAPI.swift
  JYP-iOS/JYP-iOS/Sources/Network/API/UserAPI.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/AuthService.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/BaseService.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/KeychainService.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/ServiceProviderType.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/UserService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/Components/MyPageButton.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/MyPageReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/MyPageViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/Components/OnboardingCardView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/Components/OnboardingQuestionView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/Onboarding/OnboardingOneViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/Onboarding/OnboardingTwoViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingQuestion/OnboardingQuestionJourneyViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingQuestion/OnboardingQuestionPlaceViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingQuestion/OnboardingQuestionPlanViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingQuestion/OnboardingQuestionReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingQuestionReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingSignUp/OnboardingSignUpReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingSignUp/OnboardingSignUpViewController.swift
Labels: size/xl

#107 [Bugfix/#104] 플래너 생성 이름 오류 해결
  JYP-iOS/JYP-iOS/Sources/Network/NetworkLoggerPlugin.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerName/CreatePlannerNameReactor.swift
Labels: size/s

#109 [Bugfix/#108] 메인 플래너에서 D-Day 태그 데이터 입력
  JYP-iOS/JYP-iOS/Sources/Extension/DateManager.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/Cell/JourneyCardCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/PastJourney/PastJourneyReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/ScheduledJourney/ScheduledJourneyReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPMemberStackView.swift
Labels: bug, size/m

#111 [Bugfix/#110] 플래너 생성 n박 n일 계산 로직 수정
  JYP-iOS/JYP-iOS/Sources/Extension/DateManager.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Calendar/CalendarService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Calendar/CalendarViewController.swift
Labels: bug

#113 [Feat/#103] 잘못된 code로 planner 입장 방지
  JYP-iOS/JYP-iOS/Sources/CompositionRoot.swift
  JYP-iOS/JYP-iOS/Sources/Model/JYPNetworkError.swift
  JYP-iOS/JYP-iOS/Sources/Model/PersonalityID.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/JourneyService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerDate/CreatePlannerDateViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/JoinPlanner/InputPlannerCodeBottomSheetReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/JoinPlanner/InputPlannerCodeBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/JoinPlanner/JoinErrorBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/JoinPlanner/JoinPlannerBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
Labels: size/m

#117 [Bugfix/#116] textField에 값 변경 시 x 버튼이 나타나지 않는 버그
  JYP-iOS/JYP-iOS/Sources/Extension/Rx+Ext.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPSearchTextField.swift
Labels: bug, size/m

#123 [Feat/#122] 여행 태그 셀에 숫자 추가
  JYP-iOS/JYP-iOS/Sources/Extension/UIBezierPath+Ext.swift
  JYP-iOS/JYP-iOS/Sources/Extension/UIView+Ext.swift
  JYP-iOS/JYP-iOS/Sources/Model/Tag.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/DiscussionTagSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/DiscussionView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/TagCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPTag.swift
Labels: size/m

#121 [Bugfix] 토론장 루트 페이지 셀이 화면을 벗어나는 레이아웃 수정
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerRoute/Components/Cell/RouteCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerRoute/PlannerRouteViewController.swift
Labels: size/s

#125 [Bugfix/#124] 토론장 태그 바텀 시트 닉네임 사진 레이아웃 정렬 수정
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/TagBottomSheet/Components/ProfileBoxView.swift
Labels: size/xs

#119 [Feat/#118] 토론장 피키 좋아요 버튼 네트워크 연동
  JYP-iOS/JYP-iOS/Sources/CompositionRoot.swift
  JYP-iOS/JYP-iOS/Sources/Config/UserDefaultsAccess.swift
  JYP-iOS/JYP-iOS/Sources/Model/BaseModel.swift
  JYP-iOS/JYP-iOS/Sources/Network/API/AuthAPI.swift
  JYP-iOS/JYP-iOS/Sources/Network/API/JourneyAPI.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/AuthService.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/JourneyService.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/UserService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/DiscussionReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/DiscussionView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlanReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlanView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/PlannerReactor.swift
Labels: size/m

#127 [Bug/#126] 카카오 웹 로그인이 아닌 카카오 톡으로 로그인이 안되는 버그
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingSignUp/OnboardingSignUpViewController.swift
  JYP-iOS/JYP-iOS/Sources/SceneDelegate.swift
  Project.swift
Labels: size/s

#130 [Bugfix/#129] 애플 로그인 서버 에러
  JYP-iOS/JYP-iOS/Sources/Model/DTO/AppleLoginResponse.swift
  JYP-iOS/JYP-iOS/Sources/Network/API/AuthAPI.swift
Labels: size/xs

#134 Bugfix/#133 카카오 로그인 콜백이 불리지 않음
  JYP-iOS/JYP-iOS/Sources/AppDelegate.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingSignUp/OnboardingSignUpViewController.swift
  Project.swift
Labels: bug, size/m

#135 [Bugfix/#131] 카카오톡 로그인 에러
  Project.swift
Labels: size/xs

#137 [Feat/#132] 온보딩 페이지 후 메인 페이지 이동
  JYP-iOS/JYP-iOS/Sources/CompositionRoot.swift
  JYP-iOS/JYP-iOS/Sources/Extension/StringProtocol+Ext.swift
  JYP-iOS/JYP-iOS/Sources/Network/API/JourneyAPI.swift
  JYP-iOS/JYP-iOS/Sources/Network/API/UserAPI.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/AuthService.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/UserService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/MyPageReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/MyPageViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingQuestion/OnboardingQuestionPlanViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingSignUp/OnboardingSignUpReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingSignUp/OnboardingSignUpViewController.swift
Labels: size/m
