Repository Nexters/JYP-iOS, pull requests merged in 2023-02, with the labels that each got.

#143 [Feat/#136] 플래너 삭제 UI + 네트워크 연결
  JYP-iOS/JYP-iOS/Sources/CompositionRoot.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/JourneyService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MoreView/PlannerMoreButtomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MoreView/RemovePlannerBottomSheetReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MoreView/RemovePlannerBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/Cell/JourneyCardCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/PastJourney/PastJourneyView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/ScheduledJourney/ScheduledJourneyView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
Labels: size/m

#144 [Feat/#142] 프로필 이미지 선택 바텀 시트 구현
  JYP-iOS/JYP-iOS/Sources/CompositionRoot.swift
  JYP-iOS/JYP-iOS/Sources/Config/KeychainAccess.swift
  JYP-iOS/JYP-iOS/Sources/Config/UserDefaultsAccess.swift
  JYP-iOS/JYP-iOS/Sources/Extension/UIStackView+Ext.swift
  JYP-iOS/JYP-iOS/Sources/Model/PersonalityID.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/BottomSheet/BottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/MyPageReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/CreateProfileBottomSheet/CreateProfileBottomSheetReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/CreateProfileBottomSheet/CreateProfileBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingQuestion/OnboardingQuestionJourneyViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingQuestion/OnboardingQuestionPlaceViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingQuestion/OnboardingQuestionPlanViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingQuestion/OnboardingQuestionReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingSignUp/OnboardingSignUpReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/TagBottomSheet/Components/ProfileBoxView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/TagBottomSheet/TagBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/TabBar/TabBarReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/TabBar/TabBarViewController.swift
Labels: size/l

#149 [Feat/#148] User API fetch me 적용
  JYP-iOS/JYP-iOS/Sources/CompositionRoot.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/UserService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerViewController.swift
Labels: size/s

#150 [Bugfix/#128] 지난 여행기 셀 터치 시 상세 플래너 페이지로 이동
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/PastJourney/PastJourneyView.swift
Labels: size/xs

#147 [Bugfix/#146] 프로필 바텀 시트 프로필 박스 체크 이미지 레이아웃 수정
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/CreateProfileBottomSheet/CreateProfileBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/TagBottomSheet/Components/ProfileBoxView.swift
Labels: size/s

#154 [Bugfix/#153] 여행 취향 선택 태그 박스 깨지는 버그
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPTag.swift
Labels: help wanted, size/s

#161 [Bugfix/#160] 후보 장소 추가 확인
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/Components/Cell/PikmiCollectionViewCell.swift
Labels: help wanted, size/s

#159 [Bugfix/#158] 플래너 생성 태그화면 QA 피드백 반영
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerDate/CreatePlannerDateView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerName/CreatePlannerNameViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/CreatePlanner/CreatePlannerTag/CreatePlannerTagViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/JYPTagCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/Cell/JYPTagCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPTag.swift
Labels: help wanted, size/m

#157 [Bugfix/#156] 나의 여행 첫 진입 QA 피드백 반영
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_journey_delete.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/icon_journey_delete.imageset/icon_place delet btn.svg
  JYP-iOS/JYP-iOS/Sources/Presenter/MoreView/PlannerMoreButtomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/Cell/EmptyJourneyCardCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerViewController.swift
Labels: help wanted, size/s

#163 [Bugfix/#162] 플래너 계획 루트 추가 QA 피드백 반영
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerRoute/Components/Cell/PikmiRouteCollectionReusableView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerRoute/Components/Cell/PikmiRouteCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerRoute/PlannerRouteViewController.swift
Labels: help wanted, size/s, qa

#165 [Bugfix/#164] 온보딩 페이지 QA 및 반영
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/Components/OnboardingView.swift
Labels: help wanted, size/s, qa

#167 [Feat/#166] 회원탈퇴 구현
  JYP-iOS/JYP-iOS/Sources/CompositionRoot.swift
  JYP-iOS/JYP-iOS/Sources/Config/KeychainAccess.swift
  JYP-iOS/JYP-iOS/Sources/Config/UserDefaultsAccess.swift
  JYP-iOS/JYP-iOS/Sources/Model/JYPNetworkError.swift
  JYP-iOS/JYP-iOS/Sources/Network/API/BaseAPI.swift
  JYP-iOS/JYP-iOS/Sources/Network/API/UserAPI.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/AuthService.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/KeychainService.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/UserService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MoreView/RemovePlannerBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/LogoutBottomSheet/LogoutBottomSheetReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/LogoutBottomSheet/LogoutBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/MyPageReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/MyPageViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/WithdrawBottomSheet/WithdrawBottomSheetReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/WithdrawBottomSheet/WithdrawBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPlanner/MyPlannerViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/CreateProfileBottomSheet/CreateProfileBottomSheetViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingQuestion/OnboardingQuestionReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Onboarding/OnboardingSignUp/OnboardingSignUpReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
Labels: help wanted, size/l

#170 [Build/#145] fastlane 구축
  .github/workflows/upload_testflight.yml
  .gitignore
  Gemfile
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/README.md
  fastlane/report.xml
Labels: help wanted, size/m

#169 [Feat/#168] 마이 페이지 앱 사용설명서 웹뷰
  JYP-iOS/JYP-iOS/Sources/Base/NavigationBarViewController.swift
  JYP-iOS/JYP-iOS/Sources/CompositionRoot.swift
  JYP-iOS/JYP-iOS/Sources/Config/Environment.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/MyPageViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/DiscussionReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerSearchPlaceMap/PlannerSearchPlaceMapReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/WebReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/WebViewController.swift
Labels: help wanted, size/s

#175 [Bugfix/#174] fastlane xcconfig 파일 가져오게 하기
  .github/workflows/upload_testflight.yml
  .gitignore
  JYP-iOS/JYP-iOS/Sources/Global/Environment.swift
  JYP-iOS/JYP-iOS/Sources/Global/UserDefaultsAccess.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/Components/Cell/PikmiCollectionViewCell.swift
  Project.swift
  README.md
  Tuist/Dependencies.swift
  Tuist/Signing/JYP-iOS.Debug.mobileprovision
  Tuist/Signing/JYP-iOS.Release.mobileprovision
  Tuist/Signing/development.cer.encrypted
  Tuist/Signing/development.p12.encrypted
  Tuist/Signing/release.cer.encrypted
  Tuist/Signing/release.p12.encrypted
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/README.md
  fastlane/report.xml
Labels: help wanted, size/m

#183 [Bugfix/#182] 마이 페이지에서 프로필 이미지 변경
  JYP-iOS/JYP-iOS/Sources/Presenter/MyPage/MyPageViewController.swift
Labels: help wanted, size/xs

#185 [Feat/#184] 참여코드 복사 페이지에 설명 스크롤 뷰 추가
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/step one.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/step one.imageset/Group 80495.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/step one.imageset/Group 80495@2x.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/step one.imageset/Group 80495@3x.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/step three.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/step three.imageset/Group 80496.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/step three.imageset/Group 80496@2x.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/step three.imageset/Group 80496@3x.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/step two.imageset/Contents.json
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/step two.imageset/Group 80494.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/step two.imageset/Group 80494@2x.png
  JYP-iOS/JYP-iOS/Resources/Assets.xcassets/step two.imageset/Group 80494@3x.png
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerInvite/Components/InviteStepView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerInvite/PlannerInviteViewController.swift
Labels: help wanted, size/m

#181 [Bugfix/#180] 플래너 토론장 후보 장소 레이아웃 수정
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/Components/Cell/PikmiCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/DiscussionReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/PlannerViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerRoute/Components/Cell/PikmiRouteCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerRoute/PlannerRouteReactor.swift
Labels: size/s

#179 [Bugfix/#178] 장소 검색 지도에서 검색이 안되게 막아야함
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerSearchPlaceMap/PlannerSearchPlaceMapViewController.swift
Labels: size/xs

#192 [Bugfix/#190] 여러 플래너 참여시 예전 이벤트들이 방출되는 버그
  JYP-iOS/JYP-iOS/Sources/Base/NavigationBarViewController.swift
  JYP-iOS/JYP-iOS/Sources/CompositionRoot.swift
  JYP-iOS/JYP-iOS/Sources/Extension/UINavigationController+Ext.swift
  JYP-iOS/JYP-iOS/Sources/Network/Service/JourneyService.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/Components/Cell/PikmiCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/Components/Cell/PikmiCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/DiscussionReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/Discussion/DiscussionView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/EmptyPikiCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/EmptyPikiCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/PikiCollectionReusableView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/PikiCollectionReusableViewReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/PikiCollectionViewCell.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/Cell/PikiCollectionViewCellReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlanReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlanSectionModel.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/JourenyPlan/JourneyPlanView.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/PlannerReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/PlannerViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/Planner/TagBottomSheet/TagBottomSheetReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerInvite/CompositionRoot+PlannerInvite.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerRoute/PlannerRouteReactor.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerRoute/PlannerRouteViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Planner/PlannerSearchPlaceMap/PlannerSearchPlaceMapViewController.swift
  JYP-iOS/JYP-iOS/Sources/Presenter/Resuable/JYPButton.swift
Labels: size/xl
